server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL:true}
  cache:
    type: ${SPRING_CACHE_TYPE:caffeine}

testcontainers:
  enabled: ${TESTCONTAINERS_ENABLED:false}

jwt:
  secret: ${JWT_SECRET}
  expirationMs: ${JWT_EXPIRATIONMS:3600000}

resilience4j:
  ratelimiter:
    instances:
      default:
        limitForPeriod: ${RESILIENCE4J_RATELIMITER_INSTANCES_DEFAULT_LIMITFORPERIOD:10}
        limitRefreshPeriod: ${RESILIENCE4J_RATELIMITER_INSTANCES_DEFAULT_LIMITREFRESHPERIOD:1m}
        timeoutDuration: ${RESILIENCE4J_RATELIMITER_INSTANCES_DEFAULT_TIMEOUTDURATION:500ms}
